cc_library(
    name = "multimap",
    hdrs = ["multimap.h"],
    deps = [
        "//backend:structure",
        "@com_google_absl//absl/status:statusor",
    ],
    visibility = ["//visibility:public"],
)