cc_library(
    name = "structure",
    hdrs = ["structure.h"],
    deps = [
        "//common:memory_usage",
        "//common:type",
        "//common:heterogenous_map",
        "@com_google_absl//absl/status",
        "@com_google_absl//absl/status:statusor",
    ],
    visibility = ["//visibility:public"],
)
