load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")
load("@bazel_tools//tools/build_defs/repo:git.bzl", "git_repository")

http_archive(
  name = "com_google_googletest",
  urls = ["https://github.com/google/googletest/archive/15460959cbbfa20e66ef0b5ab497367e47fc0a04.zip"],
  strip_prefix = "googletest-15460959cbbfa20e66ef0b5ab497367e47fc0a04",
  sha256 = "ca2d683a5ed38d0c9a5c5ab6a2ab67bc5ce8772444133029b2bfc5c3bf05db2f"
)


http_archive(
    name = "com_github_google_benchmark",
    urls = ["https://github.com/google/benchmark/archive/refs/tags/v1.7.0.zip"],
    strip_prefix = "benchmark-1.7.0",
    sha256 = "e0e6a0f2a5e8971198e5d382507bfe8e4be504797d75bb7aec44b5ea368fa100",
)

http_archive(
  name = "com_google_absl",
  urls = ["https://github.com/abseil/abseil-cpp/archive/eda52d053e6400d9411b1f46a1a17a959d4db11f.zip"],
  strip_prefix = "abseil-cpp-eda52d053e6400d9411b1f46a1a17a959d4db11f",
  sha256 = "41618cbfe85c498034914f4b7a0d84c5703e515c060fbddb7b9396848dc2c029"
)

http_archive(
    name = "bazel_skylib",
    urls = [
        "https://mirror.bazel.build/github.com/bazelbuild/bazel-skylib/releases/download/1.2.1/bazel-skylib-1.2.1.tar.gz",
        "https://github.com/bazelbuild/bazel-skylib/releases/download/1.2.1/bazel-skylib-1.2.1.tar.gz",
    ],
    sha256 = "f7be3474d42aae265405a592bb7da8e171919d74c16f082a5457840f06054728",
)
load("@bazel_skylib//:workspace.bzl", "bazel_skylib_workspace")
bazel_skylib_workspace()

git_repository(
    name = "boringssl",
    commit = "d345d68d5c4b5471290ebe13f090f1fd5b7e8f58",
    remote = "https://boringssl.googlesource.com/boringssl",
    shallow_since = "1663197646 +0000",
)

http_archive(
    name = "rules_foreign_cc",
    sha256 = "2a4d07cd64b0719b39a7c12218a3e507672b82a97b98c6a89d38565894cf7c51",
    strip_prefix = "rules_foreign_cc-0.9.0",
    url = "https://github.com/bazelbuild/rules_foreign_cc/archive/refs/tags/0.9.0.tar.gz",
)

load("@rules_foreign_cc//foreign_cc:repositories.bzl", "rules_foreign_cc_dependencies")

# This sets up some common toolchains for building targets. For more details, please see
# https://bazelbuild.github.io/rules_foreign_cc/0.9.0/flatten.html#rules_foreign_cc_dependencies
rules_foreign_cc_dependencies()

_ALL_CONTENT = """\
filegroup(
    name = "all_srcs",
    srcs = glob(["**"]),
    visibility = ["//visibility:public"],
)
"""

http_archive(
    name = "gperftools",
    #build_file = "@//third_party/gperftools:BUILD",
    build_file_content = _ALL_CONTENT,
    strip_prefix = "gperftools-gperftools-2.10",
    urls = [
        "https://github.com/gperftools/gperftools/archive/refs/tags/gperftools-2.10.zip",
    ],
    sha256 = "a7ad7779a0584da12c8bffffcb6020855ad936736c30ba99e75376fe7a1f446f",
)

http_archive(
    name = "com_github_google_crc32c",
    build_file = "@//third_party/crc32c:crc32c.BUILD",
    sha256 = "ac07840513072b7fcebda6e821068aa04889018f24e10e46181068fb214d7e56",
    strip_prefix = "crc32c-1.1.2",
    urls = ["https://github.com/google/crc32c/archive/1.1.2.tar.gz"],
)

http_archive(
    name = "com_github_google_snappy",
    build_file = "@//third_party/snappy:snappy.BUILD",
    sha256 = "75c1fbb3d618dd3a0483bff0e26d0a92b495bbe5059c8b4f1c962b478b6e06e7",
    strip_prefix = "snappy-1.1.9",
    urls = ["https://github.com/google/snappy/archive/1.1.9.tar.gz"],
)

http_archive(
    name = "com_github_google_leveldb",
    build_file = "@//third_party/leveldb:leveldb.BUILD",
    sha256 = "9a37f8a6174f09bd622bc723b55881dc541cd50747cbd08831c2a82d620f6d76",
    strip_prefix = "leveldb-1.23",
    urls = ["https://github.com/google/leveldb/archive/1.23.tar.gz"],
)


http_archive(
    name = "com_github_google_crc32c",
    build_file = "@//third_party/crc32c:crc32c.BUILD",
    sha256 = "ac07840513072b7fcebda6e821068aa04889018f24e10e46181068fb214d7e56",
    strip_prefix = "crc32c-1.1.2",
    urls = ["https://github.com/google/crc32c/archive/1.1.2.tar.gz"],
)

http_archive(
    name = "com_github_google_snappy",
    build_file = "@//third_party/snappy:snappy.BUILD",
    sha256 = "75c1fbb3d618dd3a0483bff0e26d0a92b495bbe5059c8b4f1c962b478b6e06e7",
    strip_prefix = "snappy-1.1.9",
    urls = ["https://github.com/google/snappy/archive/1.1.9.tar.gz"],
)

http_archive(
    name = "com_github_google_leveldb",
    build_file = "@//third_party/leveldb:leveldb.BUILD",
    sha256 = "9a37f8a6174f09bd622bc723b55881dc541cd50747cbd08831c2a82d620f6d76",
    strip_prefix = "leveldb-1.23",
    urls = ["https://github.com/google/leveldb/archive/1.23.tar.gz"],
)
