cc_library(
    name="type",
    hdrs=["type.h"],
    srcs=["type.cc"],
    deps=[],
)

cc_test(
    name = "type_test",
    srcs = ["type_test.cc"],
    deps = [
        ":type",
        "@com_google_googletest//:gtest_main",
    ],
)