name: Go

on:
  push:
    branches: [ "main" ]
    paths:
      - '.github/workflows/go.yml'
      - '**'
  pull_request:
    branches: [ "main" ]
    paths:
      - '.github/workflows/go.yml'
      - '**'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: "1.20"

    - name: Check Go sources formatting
      working-directory: ./
      run: diff=`gofmt -s -d .`; echo "$diff"; test -z "$diff"

    - name: Build
      working-directory: ./
      run: go build -v ./...

    - name: Test
      working-directory: ./
      run: go test -v ./...
