pipeline {
    agent {label 'short'}

    stages {
        stage('Build') {
            steps {
                sh 'cd go && lib/build_libcarmen.sh'
                sh 'cd go && go build ./...'
            }
        }

        stage('Test') {
            steps {
                sh 'cd go && go test ./...'
            }
        }

        stage('Parallelism Test') {
            steps {
                sh 'cd go/backend/stock/synced && go test ./... -race -run TestSyncedStock_CanBeAccessedConcurrently'
                sh 'cd go/backend/stock/synced && go test ./... -race -run TestSyncedStock_CanBeAccessedConcurrently'
                sh 'cd go/common && go test ./... -race -run TestNWaysCache_Concurrent_ReadsWrites'
                sh 'cd go/common && go test ./... -race -run TestNWaysCache_Concurrent_Sequence'
                sh 'cd go/common && go test ./... -race -run TestHash_PassThrough_Parallel'
            }
        }

        stage('Fuzzing') {
            parallel {
                stage('Fuzzing NWays Cache') {
                    agent {label 'short'}
                    steps {
                        sh 'cd go && go test ./common/ -fuzztime 3m -fuzz FuzzLruCache_RandomOps'
                    }
                }
                stage('Fuzzing LRU Cache') {
                    agent {label 'short'}
                    steps {
                        sh 'cd go && go test ./common/ -fuzztime 3m -fuzz FuzzNWays_RandomOps'
                    }
                }
                stage('Fuzzing Buffered File') {
                    agent {label 'short'}
                    steps {
                        sh 'cd go && go test ./backend/utils -fuzztime 3m -fuzz FuzzBufferedFile_RandomOps'
                    }
                }
                stage('Fuzzing Buffered Fil - data') {
                    agent {label 'short'}
                    steps {
                        sh 'cd go && go test ./backend/utils -fuzztime 3m -fuzz FuzzBufferedFile_ReadWrite'
                    }
                }
                stage('Fuzzing Stack') {
                    agent {label 'short'}
                    steps {
                        sh 'cd go && go test ./backend/stock/file -fuzztime 3m -fuzz FuzzStack_RandomOps'
                    }
                }                
                stage('Fuzzing Stock - file') {
                    agent {label 'short'}
                    steps {
                        sh 'cd go && go test ./backend/stock/file -fuzztime 3m -fuzz FuzzFileStock_RandomOps'
                    }
                }                  
                stage('Fuzzing Stock - memory') {
                    agent {label 'short'}
                    steps {
                        sh 'cd go && go test ./backend/stock/memory -fuzztime 3m -fuzz FuzzMemoryStock_RandomOps'
                    }
                }  
                stage('Fuzzing Stock - synced') {
                    agent {label 'short'}
                    steps {
                        sh 'cd go && go test ./backend/stock/memory -fuzztime 3m -fuzz FuzzSyncStock_RandomOps'
                    }
                } 
            }
        }
    }
}