pipeline {
    agent {label 'coordinator'}

    stages {
        stage('Checkout') {
            steps {
                checkout scm
                stash 'source'
            }
        }
        
        stage('Build') {
            steps {
                sh 'make'
            }
        }

        stage('Test') {
            steps {
                sh 'cd go && go test ./...'
            }
        }

        stage('Fuzzing') {
            parallel {
                stage('Parallelism Test') {
                    agent {label 'coordinator'}
                    steps {
                        unstash 'source'
                        sh 'cd go/backend/stock/synced && go test ./... -race -run TestSyncedStock_CanBeAccessedConcurrently'
                        sh 'cd go/common && go test ./... -race -run TestNWaysCache_Concurrent_ReadsWrites'
                        sh 'cd go/common && go test ./... -race -run TestNWaysCache_Concurrent_Sequence'
                        sh 'cd go/common && go test ./... -race -run TestHash_PassThrough_Parallel'
                        sh 'cd go/state/mpt && go test ./... -race -run TestWriteBuffer_CheckThatLockedNodesAreWaitedFor'
                        sh 'cd go/state/mpt && go test ./... -race -run TestWriteBuffer_ElementsCanBeAddedInParallel'
                        sh 'cd go/state/mpt && go test ./... -race -run TestWriteBuffer_ElementsCanBeAddedAndCanceledInParallel'
                    }
                }
                stage('FastMap') {
                    agent {label 'fuzzing'}
                    steps {
                        unstash 'source'
                        sh 'cd go && go test ./common -fuzztime 3h -fuzz=FuzzMapOperations'
                    }
                }
                stage('Fuzzing NWays Cache') {
                    agent {label 'fuzzing'}
                    steps {
                        unstash 'source'
                        sh 'cd go && go test ./common/ -fuzztime 3h -fuzz FuzzLruCache_RandomOps'
                    }
                }
                stage('Fuzzing LRU Cache') {
                    agent {label 'fuzzing'}
                    steps {
                        unstash 'source'
                        sh 'cd go && go test ./common/ -fuzztime 3h -fuzz FuzzNWays_RandomOps'
                    }
                }
                stage('Fuzzing Buffered File') {
                    agent {label 'fuzzing'}
                    steps {
                        unstash 'source'
                        sh 'cd go && go test ./backend/utils -fuzztime 3h -fuzz FuzzBufferedFile_RandomOps'
                    }
                }
                stage('Fuzzing Buffered Fil - data') {
                    agent {label 'fuzzing'}
                    steps {
                        unstash 'source'
                        sh 'cd go && go test ./backend/utils -fuzztime 3h -fuzz FuzzBufferedFile_ReadWrite'
                    }
                }
                stage('Fuzzing Stack') {
                    agent {label 'fuzzing'}
                    steps {
                        unstash 'source'
                        sh 'cd go && go test ./backend/stock/file -fuzztime 3h -fuzz FuzzStack_RandomOps'
                    }
                }                
                stage('Fuzzing Stock - file') {
                    agent {label 'fuzzing'}
                    steps {
                        unstash 'source'
                        sh 'cd go && go test ./backend/stock/file -fuzztime 3h -fuzz FuzzFileStock_RandomOps'
                    }
                }                  
                stage('Fuzzing Stock - synced') {
                    agent {label 'fuzzing'}
                    steps {
                        unstash 'source'
                        sh 'cd go && go test ./backend/stock/memory -fuzztime 3h -fuzz FuzzSyncStock_RandomOps'
                    }
                }
                stage('Fuzzing Live MPT - Accounts') {
                    agent {label 'fuzzing'}
                    steps {
                        unstash 'source'
                        sh 'cd go && go test ./state/mpt/ -fuzztime 3h -fuzz FuzzLiveTrie_RandomAccountOps'
                    }
                }  
                stage('Fuzzing Live MPT - Storage') {
                    agent {label 'fuzzing'}
                    steps {
                        unstash 'source'
                        sh 'cd go && go test ./state/mpt/ -fuzztime 3h -fuzz FuzzLiveTrie_RandomAccountStorageOps'
                    }
                }                  
                stage('Fuzzing Archive MPT - Accounts') {
                    agent {label 'fuzzing'}
                    steps {
                        unstash 'source'
                        sh 'cd go && go test ./state/mpt/ -fuzztime 3h -fuzz FuzzArchiveTrie_RandomAccountOps'
                    }
                }
                stage('Fuzzing Archive MPT - Storage') {
                    agent {label 'fuzzing'}
                    steps {
                        unstash 'source'
                        sh 'cd go && go test ./state/mpt/ -fuzztime 3h -fuzz FuzzArchiveTrie_RandomAccountStorageOps'
                    }
                }
            }
        }
    }
}