// Code generated by MockGen. DO NOT EDIT.
// Source: nodes.go

// Package s4 is a generated GoMock package.
package s4

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockNode is a mock of Node interface.
type MockNode struct {
	ctrl     *gomock.Controller
	recorder *MockNodeMockRecorder
}

// MockNodeMockRecorder is the mock recorder for MockNode.
type MockNodeMockRecorder struct {
	mock *MockNode
}

// NewMockNode creates a new mock instance.
func NewMockNode(ctrl *gomock.Controller) *MockNode {
	mock := &MockNode{ctrl: ctrl}
	mock.recorder = &MockNodeMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNode) EXPECT() *MockNodeMockRecorder {
	return m.recorder
}

// Check mocks base method.
func (m *MockNode) Check(source NodeSource, depth int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Check", source, depth)
	ret0, _ := ret[0].(error)
	return ret0
}

// Check indicates an expected call of Check.
func (mr *MockNodeMockRecorder) Check(source, depth interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Check", reflect.TypeOf((*MockNode)(nil).Check), source, depth)
}

// Dump mocks base method.
func (m *MockNode) Dump(source NodeSource, indent string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Dump", source, indent)
}

// Dump indicates an expected call of Dump.
func (mr *MockNodeMockRecorder) Dump(source, indent interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Dump", reflect.TypeOf((*MockNode)(nil).Dump), source, indent)
}

// GetAccount mocks base method.
func (m *MockNode) GetAccount(source NodeSource, path []Nibble) (*AccountNode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccount", source, path)
	ret0, _ := ret[0].(*AccountNode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccount indicates an expected call of GetAccount.
func (mr *MockNodeMockRecorder) GetAccount(source, path interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccount", reflect.TypeOf((*MockNode)(nil).GetAccount), source, path)
}

// GetOrCreateAccount mocks base method.
func (m *MockNode) GetOrCreateAccount(current NodeId, manager NodeManager, path []Nibble) (NodeId, *AccountNode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrCreateAccount", current, manager, path)
	ret0, _ := ret[0].(NodeId)
	ret1, _ := ret[1].(*AccountNode)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetOrCreateAccount indicates an expected call of GetOrCreateAccount.
func (mr *MockNodeMockRecorder) GetOrCreateAccount(current, manager, path interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrCreateAccount", reflect.TypeOf((*MockNode)(nil).GetOrCreateAccount), current, manager, path)
}

// GetValue mocks base method.
func (m *MockNode) GetValue(source NodeSource, path []Nibble) (*ValueNode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetValue", source, path)
	ret0, _ := ret[0].(*ValueNode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetValue indicates an expected call of GetValue.
func (mr *MockNodeMockRecorder) GetValue(source, path interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetValue", reflect.TypeOf((*MockNode)(nil).GetValue), source, path)
}

// MockNodeSource is a mock of NodeSource interface.
type MockNodeSource struct {
	ctrl     *gomock.Controller
	recorder *MockNodeSourceMockRecorder
}

// MockNodeSourceMockRecorder is the mock recorder for MockNodeSource.
type MockNodeSourceMockRecorder struct {
	mock *MockNodeSource
}

// NewMockNodeSource creates a new mock instance.
func NewMockNodeSource(ctrl *gomock.Controller) *MockNodeSource {
	mock := &MockNodeSource{ctrl: ctrl}
	mock.recorder = &MockNodeSourceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNodeSource) EXPECT() *MockNodeSourceMockRecorder {
	return m.recorder
}

// getNode mocks base method.
func (m *MockNodeSource) getNode(arg0 NodeId) (Node, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "getNode", arg0)
	ret0, _ := ret[0].(Node)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// getNode indicates an expected call of getNode.
func (mr *MockNodeSourceMockRecorder) getNode(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "getNode", reflect.TypeOf((*MockNodeSource)(nil).getNode), arg0)
}

// MockNodeManager is a mock of NodeManager interface.
type MockNodeManager struct {
	ctrl     *gomock.Controller
	recorder *MockNodeManagerMockRecorder
}

// MockNodeManagerMockRecorder is the mock recorder for MockNodeManager.
type MockNodeManagerMockRecorder struct {
	mock *MockNodeManager
}

// NewMockNodeManager creates a new mock instance.
func NewMockNodeManager(ctrl *gomock.Controller) *MockNodeManager {
	mock := &MockNodeManager{ctrl: ctrl}
	mock.recorder = &MockNodeManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNodeManager) EXPECT() *MockNodeManagerMockRecorder {
	return m.recorder
}

// createAccount mocks base method.
func (m *MockNodeManager) createAccount() (NodeId, *AccountNode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "createAccount")
	ret0, _ := ret[0].(NodeId)
	ret1, _ := ret[1].(*AccountNode)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// createAccount indicates an expected call of createAccount.
func (mr *MockNodeManagerMockRecorder) createAccount() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "createAccount", reflect.TypeOf((*MockNodeManager)(nil).createAccount))
}

// createBranch mocks base method.
func (m *MockNodeManager) createBranch() (NodeId, *BranchNode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "createBranch")
	ret0, _ := ret[0].(NodeId)
	ret1, _ := ret[1].(*BranchNode)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// createBranch indicates an expected call of createBranch.
func (mr *MockNodeManagerMockRecorder) createBranch() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "createBranch", reflect.TypeOf((*MockNodeManager)(nil).createBranch))
}

// createExtension mocks base method.
func (m *MockNodeManager) createExtension() (NodeId, *ExtensionNode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "createExtension")
	ret0, _ := ret[0].(NodeId)
	ret1, _ := ret[1].(*ExtensionNode)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// createExtension indicates an expected call of createExtension.
func (mr *MockNodeManagerMockRecorder) createExtension() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "createExtension", reflect.TypeOf((*MockNodeManager)(nil).createExtension))
}

// createValue mocks base method.
func (m *MockNodeManager) createValue() (NodeId, *ValueNode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "createValue")
	ret0, _ := ret[0].(NodeId)
	ret1, _ := ret[1].(*ValueNode)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// createValue indicates an expected call of createValue.
func (mr *MockNodeManagerMockRecorder) createValue() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "createValue", reflect.TypeOf((*MockNodeManager)(nil).createValue))
}

// getNode mocks base method.
func (m *MockNodeManager) getNode(arg0 NodeId) (Node, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "getNode", arg0)
	ret0, _ := ret[0].(Node)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// getNode indicates an expected call of getNode.
func (mr *MockNodeManagerMockRecorder) getNode(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "getNode", reflect.TypeOf((*MockNodeManager)(nil).getNode), arg0)
}

// release mocks base method.
func (m *MockNodeManager) release(arg0 NodeId) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "release", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// release indicates an expected call of release.
func (mr *MockNodeManagerMockRecorder) release(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "release", reflect.TypeOf((*MockNodeManager)(nil).release), arg0)
}
