cc_library(
    name = "depot",
    hdrs = ["depot.h"],
    deps = [
        "//backend/store:hash_tree",
        "//common:hash",
        "//common:type",
        "@com_google_absl//absl/status:status",
        "@com_google_absl//absl/status:statusor",
    ],
    visibility = ["//visibility:public"],
)
