pipeline {
    agent any

    parameters {
        string(name: 'tmpDb', defaultValue: '/var/opera/Aida/dbtmpjenkins', description: 'Temporary directory to store the state DB.')
        string(name: 'aidaDb', defaultValue: '/var/opera/Aida/mainnet-data/aida-db', description: 'Temporary directory to read Aida DB from.')
        string(name: 'firstBlockHeight', defaultValue: '1000000', description: 'First block height to import.')
        string(name: 'secondBlockHeight', defaultValue: '2000000', description: 'Second block height to import.')
    }

    stages {
        stage('Checkout') {
            steps {
                dir('Carmen') {
                	checkout scmGit(
                		branches: [[name: 'main']],
                		userRemoteConfigs: [[credentialsId:  'AidaCI_PAT', url: 'https://github.com/Fantom-foundation/Carmen.git']]
                	)
                }
                dir('Aida') {
                    checkout scmGit(
                        branches: [[name: 'origin/develop']],
                        userRemoteConfigs: [[
                            credentialsId:  'AidaCI_PAT',
                            url: 'https://github.com/Fantom-foundation/Aida.git'
                        ]]
                    )
                    sh "git submodule update --init --recursive"
                }
            }
        }

        stage('Build') {
            steps {
                // TODO - integrate recent (or tagged/branched) carmen
                //sh 'cp -r Carmen/go Aida/carmen/'
                //sh 'cd Aida && go build -o build/aida-vm-sdb ./cmd/aida-vm-sdb'
                sh 'cd Aida && make -j aida-vm-sdb'
            }
        }

        // TODO Aida tests are not passing
        //stage('Test') {
        //   steps {
        //       sh 'cd Aida && go test ./...'
        //    }
        //}

        stage('Synchronise Blocks') {
            steps {
                sh "Aida/build/aida-vm-sdb substate --aida-db  ${params.aidaDb} --db-tmp  ${params.tmpDb}  --vm-impl=lfvm --db-impl carmen --db-variant go-file --carmen-schema 5 --keep-db  --validate-state-hash 0 ${params.firstBlockHeight} "
            }
        }

        stage('Verify sync DB') {
            steps {
                sh "cd Aida/carmen/go && go run ./state/mpt/tool verify ${params.tmpDb}/state_db_carmen_go-file_${params.firstBlockHeight}/"
            }
        }

        stage('Export DB') {
            steps {
                sh "cd Aida/carmen/go && go run ./state/mpt/tool export ${params.tmpDb}/state_db_carmen_go-file_${params.firstBlockHeight}/ ${params.tmpDb}/genesis.dat"
            }
        }

        stage('Import DB') {
            steps {
                sh "cd Aida/carmen/go && go run ./state/mpt/tool import ${params.tmpDb}/genesis.dat ${params.tmpDb}/state_db_carmen_go-file_${params.firstBlockHeight}-recov/"
            }
        }

        stage('Verify recovered DB') {
            steps {
                sh "cd Aida/carmen/go && go run ./state/mpt/tool verify ${params.tmpDb}/state_db_carmen_go-file_${params.firstBlockHeight}-recov/"
            }
        }

        stage('Continue Synchronise Blocks') {
            steps {
                sh "cp ${params.tmpDb}/state_db_carmen_go-file_${params.firstBlockHeight}/statedb_info.json ${params.tmpDb}/state_db_carmen_go-file_${params.firstBlockHeight}-recov/"
                script {nextBlock=params.firstBlockHeight.toInteger()+1}
                sh "Aida/build/aida-vm-sdb substate --aida-db ${params.aidaDb} --db-src ${params.tmpDb}/state_db_carmen_go-file_${params.firstBlockHeight}-recov/ --vm-impl=lfvm --db-impl carmen --db-variant go-file --carmen-schema 5 --keep-db --validate-state-hash ${nextBlock} ${params.secondBlockHeight}"
            }
        }    

        stage('Re-verify DB') {
            steps {
                sh "cd Aida/carmen/go && go run ./state/mpt/tool verify ${params.tmpDb}/state_db_carmen_go-file_${params.firstBlockHeight}-recov/"
            }
        }  

        stage('Remove DB') {
            steps {
                sh "rm -rf ${params.tmpDb}/state_db_carmen_go-file_${params.firstBlockHeight}/"
                sh "rm -rf ${params.tmpDb}/state_db_carmen_go-file_${params.firstBlockHeight}-recov/"
            }
        }                    

}
}