name: cpp-tests

on:
  push:
    branches: [ "master" ]
    paths:
      - 'cpp/**'
  pull_request:
    branches: [ "master" ]
    paths:
      - 'cpp/**'

jobs:
  tests-check:
    name: Tests Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: bazelbuild/setup-bazelisk@v2
      - name: Mount bazel cache
        uses: actions/cache@v3
        with:
          path: "~/.cache/bazel"
          key: bazel
      - name: Run tests
        working-directory: ./cpp
        run: bazel test //...
