name: cpp-OSX

on:
  push:
    branches: [ "main" ]
    paths:
      - '.github/workflows/cpp-osx.yml'
      - 'cpp/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - '.github/workflows/cpp-osx.yml'
      - 'cpp/**'

env:
  CC: clang
  CXX: clang++

jobs:

  build:
    runs-on: macos-latest
    env:
      TEST_TMPDIR: "/Users/runner/.cache/bazel"
    steps:
    - uses: actions/checkout@v3
    - uses: bazelbuild/setup-bazelisk@v2
    - name: Mount bazel cache
      uses: actions/cache@v3
      with:
       path: "/Users/runner/.cache/bazel"
       key: bazel-cpp-osx

    - name: Run C++ tests
      working-directory: ./cpp
      run: bazel test --test_output=errors //...

