name: cpp-tests

on:
  push:
    branches: [ "main" ]
    paths:
      - '.github/workflows/cpp-tests.yml'
      - 'cpp/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - '.github/workflows/cpp-tests.yml'
      - 'cpp/**'

jobs:
  tests-check:
    name: Tests Check
    runs-on: [self-hosted, Linux, X64]
    steps:
      - name: Collect Workflow Telemetry
        uses: runforesight/workflow-telemetry-action@v1
        with:
          comment_on_pr: false

      - uses: actions/checkout@v3

      - name: Run tests
        working-directory: ./cpp
        #run: bazel test --config asan --test_output=errors //...
        run: bazel test --test_output=errors //...
