name: cpp-tests

on:
  push:
    branches: [ "master" ]
    paths:
      - '.github/workflows/cpp-tests.yml'
      - 'cpp/**'
  pull_request:
    branches: [ "master" ]
    paths:
      - '.github/workflows/cpp-tests.yml'
      - 'cpp/**'

jobs:
  tests-check:
    name: Tests Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: egor-tensin/setup-clang@v1
      - uses: bazelbuild/setup-bazelisk@v2
      - name: Mount bazel cache
        uses: actions/cache@v3
        with:
          path: "~/.cache/bazel"
          key: bazel-cpp-linux

      - name: Run tests
        working-directory: ./cpp
        run: bazel test --config asan //...
