name: cpp-tests

on:
  push:
    branches: [ "main" ]
    paths:
      - '.github/workflows/cpp-tests.yml'
      - 'cpp/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - '.github/workflows/cpp-tests.yml'
      - 'cpp/**'

env:
  CC: clang
  CXX: clang++

jobs:
  tests-check:
    name: Tests Check
    runs-on: ubuntu-20.04
    steps:
      - name: Collect Workflow Telemetry
        uses: runforesight/workflow-telemetry-action@v1
        with:
          comment_on_pr: false

      - uses: actions/checkout@v3

      - name: Set up clang
        uses: egor-tensin/setup-clang@v1
        with:
          version: 14

      - name: Set up bazel
        uses: bazelbuild/setup-bazelisk@v2

      - name: Mount bazel cache
        uses: actions/cache@v3
        with:
          path: "~/.cache/bazel"
          key: bazel-cpp-linux

      - name: Run tests
        working-directory: ./cpp
        run: bazel test --config asan --test_output=errors //...
