# Copyright (c) 2024 Fantom Foundation
# 
# Use of this software is governed by the Business Source License included
# in the LICENSE.TXT file and at fantom.foundation/bsl11.
# 
# Change Date: 2028-4-16
# 
# On the date above, in accordance with the Business Source License, use
# of this software will be governed by the GNU Lesser General Public Licence v3

name: cpp-tests

on:
  push:
    branches: [ "main" ]
    paths:
      - '.github/workflows/cpp-tests.yml'
      - 'cpp/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - '.github/workflows/cpp-tests.yml'
      - 'cpp/**'

jobs:
  tests-check:
    name: Tests Check
    runs-on: [self-hosted, Linux, X64]
    env:
        CC: clang
        CXX: clang++
    steps:
      - name: Collect Workflow Telemetry
        uses: catchpoint/workflow-telemetry-action@v2
        with:
          comment_on_pr: false

      - uses: actions/checkout@v4

      - name: Run tests
        working-directory: ./cpp
        #run: bazel test --config asan --test_output=errors //...
        run: bazel test --test_output=errors //...
