name: Go

on:
  push:
    branches: [ "main" ]
    paths:
      - '.github/workflows/go.yml'
      - 'cpp/**'
      - 'go/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - '.github/workflows/go.yml'
      - 'cpp/**'
      - 'go/**'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: egor-tensin/setup-clang@v1
    - uses: bazelbuild/setup-bazelisk@v2
    - name: Mount bazel cache
      uses: actions/cache@v3
      with:
       path: "~/.cache/bazel"
       key: bazel-go-linux

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: "1.20"

    - name: Check Go sources formatting
      working-directory: ./go
      run: diff=`gofmt -s -d .`; echo "$diff"; test -z "$diff"

    - name: Build C++ libraries
      working-directory: ./go/lib
      run: ./build_libcarmen.sh

    - name: Build
      working-directory: ./go
      run: go build -v ./...

    - name: Test
      working-directory: ./go
      run: go test -v ./...
