# Copyright (c) 2024 Fantom Foundation
# 
# Use of this software is governed by the Business Source License included
# in the LICENSE file and at fantom.foundation/bsl11.
# 
# Change Date: 2028-4-16
# 
# On the date above, in accordance with the Business Source License, use
# of this software will be governed by the GNU Lesser General Public Licence v3

name: Go

on:
  push:
    branches: [ "main" ]
    paths:
      - '.github/workflows/go.yml'
      - 'cpp/**'
      - 'go/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - '.github/workflows/go.yml'
      - 'cpp/**'
      - 'go/**'

jobs:

  build:
    runs-on: [self-hosted, Linux, X64]
    env:
      GOMEMLIMIT: "5GiB"
    steps:
    - name: Collect Workflow Telemetry
      uses: catchpoint/workflow-telemetry-action@v2
      with:
        comment_on_pr: false

    - uses: actions/checkout@v4

    - name: Check Go sources formatting
      working-directory: ./go
      run: diff=`gofmt -s -d .`; echo "$diff"; test -z "$diff"

    - name: Build C++ libraries
      working-directory: ./go/lib
      run: ./build_libcarmen.sh

    - name: Build
      working-directory: ./go
      run: go build -v ./...

    - name: Test
      working-directory: ./go
      run: go test ./... -parallel 4 -timeout 60m
