name: Go

on:
  push:
    branches: [ "master" ]
    paths:
      - '.github/workflow/go.yml'
      - 'go/**'
  pull_request:
    branches: [ "master" ]
    paths:
      - '.github/workflow/go.yml'
      - 'go/**'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build
      working-directory: ./go
      run: go build -v ./...

    - name: Test
      working-directory: ./go
      run: go test -v ./...
