name: Go

on:
  push:
    branches: [ "main" ]
    paths:
      - '.github/workflows/go.yml'
      - 'cpp/**'
      - 'go/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - '.github/workflows/go.yml'
      - 'cpp/**'
      - 'go/**'

jobs:

  build:
    runs-on: [self-hosted, Linux, X64]
    env:
      GOMEMLIMIT: "5GiB"
    steps:
    - name: Collect Workflow Telemetry
      uses: runforesight/workflow-telemetry-action@v1
      with:
        comment_on_pr: false

    - uses: actions/checkout@v3

    - name: Check Go sources formatting
      working-directory: ./go
      run: diff=`gofmt -s -d .`; echo "$diff"; test -z "$diff"

    - name: Build C++ libraries
      working-directory: ./go/lib
      run: ./build_libcarmen.sh

    - name: Build
      working-directory: ./go
      run: go build -v ./...

    - name: Test
      working-directory: ./go
      run: go test ./... -parallel 1 -timeout 60m
